apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
spec:
  replicas: 1  # Number of desired replicas
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
      - name: contact
        image: mohammadthaheer/contact:latest
        ports:
        - containerPort: 3000  # Port your application listens on
